version: "3.7"
services:
  web:
    image: "vijayjeyam/qualstra2:2.0.0"
    ports:
      - "80:9090"
  db:
    image: "qualstradb:1.0"
    ports:
      - "8080:8082"
      - "9092:9092"
    container_name: qualstradb

