version: '3.7'
networks:
  default:
    external:
      name: uat
services:
    uat_mongodbinfra:
        image: 'bitnami/mongodb:4.2'
        container_name: ${MONGO_DBHOST}
        ports:
            - '${MONGO_EXT_PORT}:${MONGO_PORT}'
        volumes:
            - 'uat_mongodbinfra_data:/bitnami'
        environment:
            - MONGODB_ENABLE_DIRECTORY_PER_DB=${MONGO_ENABLE_DIRECTORY_PER_DB}
            - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGODB_USERNAME=${MONGO_USER}
            - MONGODB_PASSWORD=${MONGO_PASSWORD}
            - MONGODB_DATABASE=${MONGO_DB}
    uat_eureka:
        image: 'dev/eureka'
        container_name: ${EUREKA_HOST}
        hostname: ${EUREKA_HOST}
        volumes:
            - 'uat_eureka_data:/eureka'
        ports:
            - '${EUREKA_EXT_PORT}:${EUREKA_PORT}'
        environment:
            - EUREKA_PORT=${EUREKA_PORT}
    uat_gateway:
        image: 'dev/gateway'
        container_name: uatgateway
        volumes:
            - 'uat_gateway_data:/eureka'
        ports:
            - '${GATEWAY_EXT_PORT}:${GATEWAY_PORT}'
        environment:
            - GATEWAY_PORT=${GATEWAY_PORT}
            - EUREKA_HOST=${EUREKA_HOST}
            - EUREKA_PORT=${EUREKA_PORT}
            - UI_HOST=${UI_HOST}
        depends_on:
            - uat_eureka
    uat_db:
        image: "dev/devqualstrah2db"
        ports:
          - "9014:9014"
          - "9015:9015"
        container_name: uatqualstrah2db
    
    uat_ui:
        image: 'dev/q2ui'
        container_name: uatui
        volumes:
            - 'uat_ui_data:/uat_ui_data'
        ports:
            - '${UI_EXT_PORT}:${UI_PORT}'
        environment:
            - EUREKA_HOST=${EUREKA_HOST}
            - EUREKA_PORT=${EUREKA_PORT}
            
    uat_app:
        image: 'dev/qualstra'
        container_name: uatapp
        volumes:
            - 'uat_ui_data:/APP'
            - '/home/devserver/qualstra/uatresdir:/home/devserver/qualstra/uatresdir'
        ports:
            - '${APP_EXT_PORT}:${APP_PORT}'
        environment:
            - EUREKA_HOST=${EUREKA_HOST}
            - EUREKA_PORT=${EUREKA_PORT}
            - APP_PORT=${APP_PORT}
            - APP_RESDIR=${APP_RESDIR}
            - POSTGRESQL_DBHOST=${POSTGRESQL_DBHOST}
            - POSTGRESQL_PORT=${POSTGRESQL_PORT}
            - POSTGRESQL_USER=${POSTGRESQL_USER}
            - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
            - POSTGRESQL_DB=${POSTGRESQL_DB}
            
    uat_attribute:
        image: 'dev/attrservice'
        container_name: uatattribute
        volumes:
            - 'uat_attribute_data:/attribute'
        environment:
            - EUREKA_HOST=${EUREKA_HOST}
            - EUREKA_PORT=${EUREKA_PORT}
            - MONGO_HOST=${MONGO_DBHOST}
            - MONGO_PORT=${MONGO_PORT}
            
    uat_postgres:
        image: postgres:16-alpine
        container_name: ${POSTGRESQL_DBHOST}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "${POSTGRESQL_EXT_PORT}:${POSTGRESQL_PORT}"
        environment:
            - POSTGRES_DB=${POSTGRESQL_DB}
            - POSTGRES_USER=${POSTGRESQL_USER}
            - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
        healthcheck:
            test: "pg_isready -U postgres"


volumes:
    uat_eureka_data:
        driver: local
    uat_gateway_data:
        driver: local
    uat_mongodbinfra_data:
        driver: local
    uat_ui_data:
        driver: local
    uat_APP_data:
        driver: local
    uat_attribute_data:
        driver: local
    postgres_data:
        driver: local

